language: haskell
install:
  - npm install -g elm
  - elm-package install -y

before_script:
    - elm-make --yes --output raw-test.js tests/Main.elm
    - bash elm-stuff/packages/laszlopandy/elm-console/1.1.1/elm-io.sh raw-test.js test.js

script: node test.js
